### ISSUE TITLE
Switch to a more sensible versioning scheme

### ISSUE THREAD

**Issue by nox** [hyperium/headers#20]
Having version numbers such as `0.0.3` for `headers-ext` means that you can never release a non-breaking change to that crate (`0.0.z` isn't considered compatible with any other version by cargo). Could you make new releases with at least `0.1.0` for the version numbers?

Cc @Eijebong

**Comment by seanmonstar** [comment]
Yea, this was actually intentional. I'm hoping to release the main crate, but wasn't ready to solidify the API without some reviews. I was thinking of releasing it as `headers` (agdubs said she'd be willing to transfer the crate name), or there is `http-headers`, or we could make it part of `http` directly...

**Comment by seanmonstar** [comment]
cc @carllerche

**Comment by seanmonstar** [comment]
Filed https://github.com/hyperium/http/issues/264 around location of the crate.

**Comment by nox** [comment]
So, can we switch? For example I want to bump base64 here but that means that it *will* be a breaking change for the sheer fact that 0.0.3 to 0.0.4 is a breaking change.

**Comment by Eijebong** [comment]
FWIW the bump has already been done :p

**Comment by seanmonstar** [comment]
I'm in the process of making some real breaking changes around the trait (#24), so it's useful that it's not published at 0.1 yet.

**Comment by seanmonstar** [comment]
I've published `headers` as v0.2.0 for now. I don't plan to announce it at this version though, it's mostly to help Servo and iteration.
